# Generated by Django 2.1.7 on 2019-04-18 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareLife', '0003_auto_20190329_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='bedrooms',
            field=models.Field(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
