# Generated by Django 2.1.7 on 2019-04-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareLife', '0005_auto_20190418_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
