# Generated by Django 2.1.7 on 2019-04-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareLife', '0006_auto_20190418_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_size', models.CharField(max_length=70)),
                ('bedrooms', models.CharField(blank=True, max_length=200)),
                ('bathrooms', models.CharField(blank=True, max_length=200)),
                ('garage_size', models.CharField(blank=True, max_length=200)),
                ('year_built', models.CharField(blank=True, max_length=70)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=70)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shareLife.Location')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shareLife.Post')),
            ],
        ),
    ]
