# Generated by Django 2.1.7 on 2019-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareLife', '0008_auto_20190418_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='garage_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='property_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year_built',
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
